//
// PageAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PageAPI {

    /**
     
     
     - parameter name: (path)  
     - parameter clientId: (query) The client ID of the placement owner. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func pageControllerFetchActivePlacements(name: String, clientId: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [FetchActivePlacementsResponseDto]?, _ error: Error?) -> Void)) -> RequestTask {
        return pageControllerFetchActivePlacementsWithRequestBuilder(name: name, clientId: clientId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     
     - GET /pages/{name}/placements
     - Fetch active placements of the page.
     - parameter name: (path)  
     - parameter clientId: (query) The client ID of the placement owner. 
     - returns: RequestBuilder<[FetchActivePlacementsResponseDto]> 
     */
    open class func pageControllerFetchActivePlacementsWithRequestBuilder(name: String, clientId: String) -> RequestBuilder<[FetchActivePlacementsResponseDto]> {
        var localVariablePath = "/pages/{name}/placements"
        let namePreEscape = "\(APIHelper.mapValueToPathItem(name))"
        let namePostEscape = namePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{name}", with: namePostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "clientId": (wrappedValue: clientId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[FetchActivePlacementsResponseDto]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
