//
// AdGroupReviewTargetStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AdGroupReviewTargetStatus: String, Codable, CaseIterable {
    case approve = "APPROVE"
    case reject = "REJECT"
}
