//
// AdGroupBudgetType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AdGroupBudgetType: String, Codable, CaseIterable {
    case dailyBudget = "DAILY_BUDGET"
    case totalBudgetInPeriod = "TOTAL_BUDGET_IN_PERIOD"
    case maxBudgetPerDay = "MAX_BUDGET_PER_DAY"
}
