//
// BannerSuggestionResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BannerSuggestionResponseDto: Codable, JSONEncodable, Hashable {

    public var suggestions: [BannerSuggestionDto]
    public var placement: SuggestionResponsePlacementType
    public var metadata: AnyCodable

    public init(suggestions: [BannerSuggestionDto], placement: SuggestionResponsePlacementType, metadata: AnyCodable) {
        self.suggestions = suggestions
        self.placement = placement
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case suggestions
        case placement
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(suggestions, forKey: .suggestions)
        try container.encode(placement, forKey: .placement)
        try container.encode(metadata, forKey: .metadata)
    }
}

