//
// CampaignWithCreditUsed.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CampaignWithCreditUsed: Codable, JSONEncodable, Hashable {

    public var freeCreditUsed: Double
    public var paidCreditUsed: Double
    public var totalCreditUsed: Double
    public var id: String
    public var title: String

    public init(freeCreditUsed: Double, paidCreditUsed: Double, totalCreditUsed: Double, id: String, title: String) {
        self.freeCreditUsed = freeCreditUsed
        self.paidCreditUsed = paidCreditUsed
        self.totalCreditUsed = totalCreditUsed
        self.id = id
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case freeCreditUsed
        case paidCreditUsed
        case totalCreditUsed
        case id
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(freeCreditUsed, forKey: .freeCreditUsed)
        try container.encode(paidCreditUsed, forKey: .paidCreditUsed)
        try container.encode(totalCreditUsed, forKey: .totalCreditUsed)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
    }
}

