//
// CategoryWithPath.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CategoryWithPath: Codable, JSONEncodable, Hashable {

    public var id: String
    public var idOnStore: String
    public var storeId: String
    public var name: String
    public var parentId: String?
    public var deletedAt: Date?
    public var path: [String]

    public init(id: String, idOnStore: String, storeId: String, name: String, parentId: String?, deletedAt: Date?, path: [String]) {
        self.id = id
        self.idOnStore = idOnStore
        self.storeId = storeId
        self.name = name
        self.parentId = parentId
        self.deletedAt = deletedAt
        self.path = path
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case idOnStore
        case storeId
        case name
        case parentId
        case deletedAt
        case path
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(idOnStore, forKey: .idOnStore)
        try container.encode(storeId, forKey: .storeId)
        try container.encode(name, forKey: .name)
        try container.encode(parentId, forKey: .parentId)
        try container.encode(deletedAt, forKey: .deletedAt)
        try container.encode(path, forKey: .path)
    }
}

