//
// CheckRegistrationResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckRegistrationResponseDto: Codable, JSONEncodable, Hashable {

    public var registration: Bool

    public init(registration: Bool) {
        self.registration = registration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case registration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(registration, forKey: .registration)
    }
}

