//
// CountCost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CountCost: Codable, JSONEncodable, Hashable {

    public var count: Double?
    public var cost: Double?

    public init(count: Double? = nil, cost: Double? = nil) {
        self.count = count
        self.cost = cost
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case cost
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(cost, forKey: .cost)
    }
}

