//
// CreateTransactionResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateTransactionResponseDto: Codable, JSONEncodable, Hashable {

    public var params: IamportPaymentParams
    public var iamportId: String

    public init(params: IamportPaymentParams, iamportId: String) {
        self.params = params
        self.iamportId = iamportId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case params
        case iamportId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(params, forKey: .params)
        try container.encode(iamportId, forKey: .iamportId)
    }
}

