//
// CreateSellerDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateSellerDto: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: nil, maxLength: nil, pattern: "/clientNameRegex/")
    public var name: String
    public var userEmail: String
    public var sellerIdOnStore: String?

    public init(name: String, userEmail: String, sellerIdOnStore: String? = nil) {
        self.name = name
        self.userEmail = userEmail
        self.sellerIdOnStore = sellerIdOnStore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case userEmail
        case sellerIdOnStore
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(userEmail, forKey: .userEmail)
        try container.encodeIfPresent(sellerIdOnStore, forKey: .sellerIdOnStore)
    }
}

