//
// CreateChatGroupDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateChatGroupDto: Codable, JSONEncodable, Hashable {

    public var id: String
    public var customerId: String
    public var isAnonymous: Bool
    public var clientId: String

    public init(id: String, customerId: String, isAnonymous: Bool, clientId: String) {
        self.id = id
        self.customerId = customerId
        self.isAnonymous = isAnonymous
        self.clientId = clientId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case customerId
        case isAnonymous
        case clientId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(customerId, forKey: .customerId)
        try container.encode(isAnonymous, forKey: .isAnonymous)
        try container.encode(clientId, forKey: .clientId)
    }
}

