//
// CreateChatRecommendationResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateChatRecommendationResponseDto: Codable, JSONEncodable, Hashable {

    public var id: String
    public var explanation: String
    public var dialogueId: Double
    public var productIds: [String]
    public var createdAt: Date

    public init(id: String, explanation: String, dialogueId: Double, productIds: [String], createdAt: Date) {
        self.id = id
        self.explanation = explanation
        self.dialogueId = dialogueId
        self.productIds = productIds
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case explanation
        case dialogueId
        case productIds
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(explanation, forKey: .explanation)
        try container.encode(dialogueId, forKey: .dialogueId)
        try container.encode(productIds, forKey: .productIds)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

