//
// DashboardAdGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardAdGroup: Codable, JSONEncodable, Hashable {

    public enum BudgetType: String, Codable, CaseIterable {
        case dailyBudget = "DAILY_BUDGET"
        case totalBudgetInPeriod = "TOTAL_BUDGET_IN_PERIOD"
        case maxBudgetPerDay = "MAX_BUDGET_PER_DAY"
    }
    public var metric: BaseAdMetric
    public var id: String
    public var title: String
    public var startsAt: Date
    public var endsAt: Date?
    public var budgetType: BudgetType
    public var maxBudgetPerDay: Double
    public var totalBudgetInPeriod: Double?
    public var activated: Bool

    public init(metric: BaseAdMetric, id: String, title: String, startsAt: Date, endsAt: Date?, budgetType: BudgetType, maxBudgetPerDay: Double, totalBudgetInPeriod: Double?, activated: Bool) {
        self.metric = metric
        self.id = id
        self.title = title
        self.startsAt = startsAt
        self.endsAt = endsAt
        self.budgetType = budgetType
        self.maxBudgetPerDay = maxBudgetPerDay
        self.totalBudgetInPeriod = totalBudgetInPeriod
        self.activated = activated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metric
        case id
        case title
        case startsAt
        case endsAt
        case budgetType
        case maxBudgetPerDay
        case totalBudgetInPeriod
        case activated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(metric, forKey: .metric)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(startsAt, forKey: .startsAt)
        try container.encode(endsAt, forKey: .endsAt)
        try container.encode(budgetType, forKey: .budgetType)
        try container.encode(maxBudgetPerDay, forKey: .maxBudgetPerDay)
        try container.encode(totalBudgetInPeriod, forKey: .totalBudgetInPeriod)
        try container.encode(activated, forKey: .activated)
    }
}

