//
// FetchCartResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FetchCartResponseDto: Codable, JSONEncodable, Hashable {

    public var data: AnyCodable
    public var product: Product
    public var id: String
    public var cartId: String
    public var productId: String
    public var customerId: String
    public var clientId: String
    public var cartDate: Date
    public var createdAt: Date

    public init(data: AnyCodable, product: Product, id: String, cartId: String, productId: String, customerId: String, clientId: String, cartDate: Date, createdAt: Date) {
        self.data = data
        self.product = product
        self.id = id
        self.cartId = cartId
        self.productId = productId
        self.customerId = customerId
        self.clientId = clientId
        self.cartDate = cartDate
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case product
        case id
        case cartId
        case productId
        case customerId
        case clientId
        case cartDate
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(product, forKey: .product)
        try container.encode(id, forKey: .id)
        try container.encode(cartId, forKey: .cartId)
        try container.encode(productId, forKey: .productId)
        try container.encode(customerId, forKey: .customerId)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(cartDate, forKey: .cartDate)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

