//
// FetchAdGroupCampaignWithCreditUsedResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FetchAdGroupCampaignWithCreditUsedResponseDto: Codable, JSONEncodable, Hashable {

    public var campaign: CampaignWithCreditUsed
    public var adGroup: AdGroupWithCreditUsed
    public var placement: PlacementTitle

    public init(campaign: CampaignWithCreditUsed, adGroup: AdGroupWithCreditUsed, placement: PlacementTitle) {
        self.campaign = campaign
        self.adGroup = adGroup
        self.placement = placement
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case campaign
        case adGroup
        case placement
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(campaign, forKey: .campaign)
        try container.encode(adGroup, forKey: .adGroup)
        try container.encode(placement, forKey: .placement)
    }
}

