//
// FetchAdGroupTargetKeysResponseItemsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FetchAdGroupTargetKeysResponseItemsDto: Codable, JSONEncodable, Hashable {

    public var selectValues: [AdGroupTargetValue]
    public var id: String
    public var storeId: String
    public var name: String
    public var label: String
    public var createdAt: Date
    public var deletedAt: Date

    public init(selectValues: [AdGroupTargetValue], id: String, storeId: String, name: String, label: String, createdAt: Date, deletedAt: Date) {
        self.selectValues = selectValues
        self.id = id
        self.storeId = storeId
        self.name = name
        self.label = label
        self.createdAt = createdAt
        self.deletedAt = deletedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case selectValues
        case id
        case storeId
        case name
        case label
        case createdAt
        case deletedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(selectValues, forKey: .selectValues)
        try container.encode(id, forKey: .id)
        try container.encode(storeId, forKey: .storeId)
        try container.encode(name, forKey: .name)
        try container.encode(label, forKey: .label)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(deletedAt, forKey: .deletedAt)
    }
}

