//
// FetchMetricsOnSellerAdGroupDashboardResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FetchMetricsOnSellerAdGroupDashboardResponseDto: Codable, JSONEncodable, Hashable {

    public var summary: AdMetric
    public var metrics: [TimeSeriesAdMetric]

    public init(summary: AdMetric, metrics: [TimeSeriesAdMetric]) {
        self.summary = summary
        self.metrics = metrics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case summary
        case metrics
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(summary, forKey: .summary)
        try container.encode(metrics, forKey: .metrics)
    }
}

