//
// FetchAllExchangeRatesResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FetchAllExchangeRatesResponseDto: Codable, JSONEncodable, Hashable {

    public var exchangeRates: [FetchExchangeRateResponseDto]

    public init(exchangeRates: [FetchExchangeRateResponseDto]) {
        self.exchangeRates = exchangeRates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case exchangeRates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(exchangeRates, forKey: .exchangeRates)
    }
}

