//
// FetchMetricsOnDashboardResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FetchMetricsOnDashboardResponseDto: Codable, JSONEncodable, Hashable {

    public var summary: Metric
    public var graph: [DailyMetric]

    public init(summary: Metric, graph: [DailyMetric]) {
        self.summary = summary
        self.graph = graph
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case summary
        case graph
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(summary, forKey: .summary)
        try container.encode(graph, forKey: .graph)
    }
}

