//
// Figure.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Figure: Codable, JSONEncodable, Hashable {

    public var roas: Double?
    public var click: Double?
    public var purchase: Double?
    public var addToCart: Double?
    public var conversion: Double?
    public var impression: Double?
    public var impressedVisitor: Double?

    public init(roas: Double? = nil, click: Double? = nil, purchase: Double? = nil, addToCart: Double? = nil, conversion: Double? = nil, impression: Double? = nil, impressedVisitor: Double? = nil) {
        self.roas = roas
        self.click = click
        self.purchase = purchase
        self.addToCart = addToCart
        self.conversion = conversion
        self.impression = impression
        self.impressedVisitor = impressedVisitor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roas
        case click
        case purchase
        case addToCart
        case conversion
        case impression
        case impressedVisitor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(roas, forKey: .roas)
        try container.encodeIfPresent(click, forKey: .click)
        try container.encodeIfPresent(purchase, forKey: .purchase)
        try container.encodeIfPresent(addToCart, forKey: .addToCart)
        try container.encodeIfPresent(conversion, forKey: .conversion)
        try container.encodeIfPresent(impression, forKey: .impression)
        try container.encodeIfPresent(impressedVisitor, forKey: .impressedVisitor)
    }
}

