//
// GetMeResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMeResponseDto: Codable, JSONEncodable, Hashable {

    public enum ClientType: String, Codable, CaseIterable {
        case admin = "ADMIN"
        case store = "STORE"
        case seller = "SELLER"
    }
    public var user: GetMeUserDto
    public var clientType: ClientType

    public init(user: GetMeUserDto, clientType: ClientType) {
        self.user = user
        self.clientType = clientType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case clientType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(user, forKey: .user)
        try container.encode(clientType, forKey: .clientType)
    }
}

