//
// GetRedirectResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRedirectResponseDto: Codable, JSONEncodable, Hashable {

    public var redirect: String

    public init(redirect: String) {
        self.redirect = redirect
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirect
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(redirect, forKey: .redirect)
    }
}

