//
// InviteSellerResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InviteSellerResponseDto: Codable, JSONEncodable, Hashable {

    public var sellerId: String

    public init(sellerId: String) {
        self.sellerId = sellerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sellerId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sellerId, forKey: .sellerId)
    }
}

