//
// Order.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Order: Codable, JSONEncodable, Hashable {

    public var products: [AnyCodable]
    public var data: AnyCodable
    public var id: String
    public var orderId: String
    public var customerId: String
    public var clientId: String
    public var orderDate: Date
    public var createdAt: Date

    public init(products: [AnyCodable], data: AnyCodable, id: String, orderId: String, customerId: String, clientId: String, orderDate: Date, createdAt: Date) {
        self.products = products
        self.data = data
        self.id = id
        self.orderId = orderId
        self.customerId = customerId
        self.clientId = clientId
        self.orderDate = orderDate
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case products
        case data
        case id
        case orderId
        case customerId
        case clientId
        case orderDate
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(products, forKey: .products)
        try container.encode(data, forKey: .data)
        try container.encode(id, forKey: .id)
        try container.encode(orderId, forKey: .orderId)
        try container.encode(customerId, forKey: .customerId)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(orderDate, forKey: .orderDate)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

