//
// PlacementInjectorDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlacementInjectorDto: Codable, JSONEncodable, Hashable {

    public var grid: GridInjectorDto?

    public init(grid: GridInjectorDto? = nil) {
        self.grid = grid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case grid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(grid, forKey: .grid)
    }
}

