//
// ProcessSellerCreditDecreaseRequestDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProcessSellerCreditDecreaseRequestDto: Codable, JSONEncodable, Hashable {

    public var action: CreditDecreaseRequestAction
    public var amount: Double?
    public var rejectionReason: String?

    public init(action: CreditDecreaseRequestAction, amount: Double? = nil, rejectionReason: String? = nil) {
        self.action = action
        self.amount = amount
        self.rejectionReason = rejectionReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case amount
        case rejectionReason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(rejectionReason, forKey: .rejectionReason)
    }
}

