//
// ProductDetailDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductDetailDto: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var data: AnyCodable?

    public init(description: String? = nil, data: AnyCodable? = nil) {
        self.description = description
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

