//
// ProductFilterOperationDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductFilterOperationDto: Codable, JSONEncodable, Hashable {

    public var equalTo: AnyCodable?
    public var not: AnyCodable?
    public var contains: String?

    public init(equalTo: AnyCodable? = nil, not: AnyCodable? = nil, contains: String? = nil) {
        self.equalTo = equalTo
        self.not = not
        self.contains = contains
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case equalTo
        case not
        case contains
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(equalTo, forKey: .equalTo)
        try container.encodeIfPresent(not, forKey: .not)
        try container.encodeIfPresent(contains, forKey: .contains)
    }
}

