//
// RegisterDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterDto: Codable, JSONEncodable, Hashable {

    public var email: String
    public var code: String
    public var password: String
    public var emailReceiptAgreed: Bool

    public init(email: String, code: String, password: String, emailReceiptAgreed: Bool) {
        self.email = email
        self.code = code
        self.password = password
        self.emailReceiptAgreed = emailReceiptAgreed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case code
        case password
        case emailReceiptAgreed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(code, forKey: .code)
        try container.encode(password, forKey: .password)
        try container.encode(emailReceiptAgreed, forKey: .emailReceiptAgreed)
    }
}

