//
// Retriever.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Retriever: Codable, JSONEncodable, Hashable {

    public enum Matcher: String, Codable, CaseIterable {
        case exact = "exact"
        case endswith = "endsWith"
        case startswith = "startsWith"
        case contains = "contains"
    }
    public var path: String
    public var attribute: String
    public var matcher: Matcher?

    public init(path: String, attribute: String, matcher: Matcher? = nil) {
        self.path = path
        self.attribute = attribute
        self.matcher = matcher
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case attribute
        case matcher
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        try container.encode(attribute, forKey: .attribute)
        try container.encodeIfPresent(matcher, forKey: .matcher)
    }
}

