//
// SellerInvitationExistenceResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SellerInvitationExistenceResponseDto: Codable, JSONEncodable, Hashable {

    public var isExist: Bool

    public init(isExist: Bool) {
        self.isExist = isExist
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isExist
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isExist, forKey: .isExist)
    }
}

