//
// Store.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Store: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case platform = "PLATFORM"
        case inHouse = "IN_HOUSE"
    }
    public enum SolutionType: String, Codable, CaseIterable {
        case selfDeveloped = "SELF_DEVELOPED"
        case cafe24 = "CAFE24"
    }
    public var id: String
    public var type: ModelType
    public var client: Client
    public var solutionType: SolutionType?
    public var createdAt: Date
    public var deletedAt: Date?

    public init(id: String, type: ModelType, client: Client, solutionType: SolutionType?, createdAt: Date, deletedAt: Date?) {
        self.id = id
        self.type = type
        self.client = client
        self.solutionType = solutionType
        self.createdAt = createdAt
        self.deletedAt = deletedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case client
        case solutionType
        case createdAt
        case deletedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(client, forKey: .client)
        try container.encode(solutionType, forKey: .solutionType)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(deletedAt, forKey: .deletedAt)
    }
}

