//
// SuggestionMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SuggestionMetadata: Codable, JSONEncodable, Hashable {

    public var isBaseline: Bool

    public init(isBaseline: Bool) {
        self.isBaseline = isBaseline
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isBaseline
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isBaseline, forKey: .isBaseline)
    }
}

