//
// SystemSetting.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemSetting: Codable, JSONEncodable, Hashable {

    public var version: Double
    public var corcaClientId: String
    public var createdAt: Date

    public init(version: Double, corcaClientId: String, createdAt: Date) {
        self.version = version
        self.corcaClientId = corcaClientId
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case corcaClientId
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
        try container.encode(corcaClientId, forKey: .corcaClientId)
        try container.encode(createdAt, forKey: .createdAt)
    }
}

