//
// TransactionPaymentCard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionPaymentCard: Codable, JSONEncodable, Hashable {

    public var cardCompany: String
    public var cardNumber: String

    public init(cardCompany: String, cardNumber: String) {
        self.cardCompany = cardCompany
        self.cardNumber = cardNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cardCompany
        case cardNumber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cardCompany, forKey: .cardCompany)
        try container.encode(cardNumber, forKey: .cardNumber)
    }
}

