//
// TutorialRequestDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TutorialRequestDto: Codable, JSONEncodable, Hashable {

    public enum Category: String, Codable, CaseIterable {
        case seller = "seller"
        case store = "store"
    }
    public var category: Category
    public var stage: [Double]?
    public var isFinished: Bool?

    public init(category: Category, stage: [Double]? = nil, isFinished: Bool? = nil) {
        self.category = category
        self.stage = stage
        self.isFinished = isFinished
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case stage
        case isFinished
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(category, forKey: .category)
        try container.encodeIfPresent(stage, forKey: .stage)
        try container.encodeIfPresent(isFinished, forKey: .isFinished)
    }
}

