//
// Tutorial.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Tutorial: Codable, JSONEncodable, Hashable {

    public enum Category: String, Codable, CaseIterable {
        case seller = "seller"
        case store = "store"
    }
    public var email: String
    public var category: Category
    public var stage: [Double]
    public var isFinished: Bool
    public var createdAt: Date
    public var updatedAt: Date

    public init(email: String, category: Category, stage: [Double], isFinished: Bool, createdAt: Date, updatedAt: Date) {
        self.email = email
        self.category = category
        self.stage = stage
        self.isFinished = isFinished
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case category
        case stage
        case isFinished
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(category, forKey: .category)
        try container.encode(stage, forKey: .stage)
        try container.encode(isFinished, forKey: .isFinished)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

