//
// UpdateUserDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateUserDto: Codable, Hashable {

    public enum Role: Double, Codable, CaseIterable {
        case _0 = 0
        case _1 = 1
        case _2 = 2
    }

    public var role: Role

    public init(role: Role) {
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
    }
}
