//
// UpdateMeDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateMeDto: Codable, JSONEncodable, Hashable {

    public var emailReceiptAgreed: Bool

    public init(emailReceiptAgreed: Bool) {
        self.emailReceiptAgreed = emailReceiptAgreed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emailReceiptAgreed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(emailReceiptAgreed, forKey: .emailReceiptAgreed)
    }
}

